name: voice_arduino
version: 0.5.0
description: Demonstrates how to use the `flutter_bluetooth_serial_ble` plugin.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  speech_to_text: ^6.6.1
  avatar_glow: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial_ble:
    path: ../
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
